lib/index.coffee
lib/price-import.coffee
lib/product-import.coffee
test/integration.spec.coffee
test/integration/price-import.spec.coffee
test/price-import.spec.coffee

@hajoeichler @emmenko please have a look.

sphere price importer

---

lib/product-import.coffee
test/product-import.spec.coffee

Config to sync module to blacklist all price updates and whitelist all other update actions

Blacklist price updates

---

lib/price-import.coffee
test/integration/price-import.spec.coffee
test/price-import.spec.coffee

@panshul007 and @emmenko please review

Adjust price importer to new input format.

---

lib/product-import.coffee
samples/sample-category.json
samples/sample-product-type.json
samples/sample-tax-category.json
test/integration.spec.coffee

Add more tests for variant update.
Update error handling -> return err.body on rejections.
Ensure ProductType, Categories, Tax Categories before running integration tests.

Fix variant updates

---

lib/index.coffee
lib/product-discount-import.coffee
test/integration/product-discount-import.spec.coffee

@panshul007 please review.
In general we will provide a key/externalId for the discounts via the API to allow a better matching instead of the english name.

Product discount import

---

test/integration.spec.coffee

Fix for duplicate slug test in parallel as api sometimes fails to validate duplicate slugs.

Fix for duplicate slug test

---

README.md
samples/sample-product-discounts.json
samples/sample-products.json

Documentation for all modules are linked to the wiki.
WIP -> product discounts importer

Documentation

---

lib/enum-validator.coffee
test/enum-validator.spec.coffee

Handles an array of values for a Set of Enums.
Generates individual update actions for each value from the array of values.

Update - handle array of enum set values.

---

lib/index.coffee
lib/product-import.coffee
lib/unknown-attributes-filter.coffee
test/integration.spec.coffee
test/unknown-attributes-filter.spec.coffee

[ ] Add filter class - done
[ ] Add tests  for the the filter class - done
[ ] Integrate filter into the product-importer - WIP

WIP: Ignore undefined attributes

---

lib/price-import.coffee
samples/sample-prices.json
test/integration/price-import.spec.coffee

Resolve references in price:
* customerGroup
* channel

Price Import reference resolution

---

lib/price-import.coffee
package.json

@emmenko @panshul007 please review

feat(priceImport): add chunk size option to price import

---

lib/product-import.coffee
readme/product-import.md

feat(productImport): add option to filter actions

---

lib/product-import.coffee
readme/product-import.md

@panshul007 @hajoeichler 
We need this to be able to find out the SKUs and IDs of all variants, since a typical import only gets the SKUs

feat(filterActions): pass existing and new product to filter function

---

lib/common-utils.coffee
lib/price-import.coffee
lib/product-import.coffee
test/common-utils.spec.coffee
test/product-import.spec.coffee

@butenkor @panshul007 @emmenko @hajoeichler 
closes #5

feat(productImport): split query into chunks that dont exceed the query limit

---

lib/common-utils.coffee
lib/product-import.coffee
package.json
test/common-utils.spec.coffee
test/product-import.spec.coffee

fix(utils): consider different sku lenghts when splitting into chunks

---

lib/product-import.coffee

prints the complete product to console. Not very useful.

remove: unwanted debug logging messages.

---

lib/product-import.coffee
test/integration/product-import.spec.coffee
test/product-import.spec.coffee

The complete process crashes with an unhandled rejection error when the sphere product import is not able to resolve a category.

Reject when a category is not found

---

lib/product-import.coffee
readme/product-import.md

cc/ @emmenko @butenkor @panshul007

add support for providing an array of actions that should be filtered out

---

.gitignore
lib/product-import.coffee
readme/product-import.md
samples/sample-type.json
test/integration.spec.coffee

Fix for https://github.com/sphereio/sphere-product-import/issues/87

Add support for custom price fields - resolve price refence

---

lib/product-import.coffee
package.json
readme/product-import.md
test/integration.spec.coffee
test/integration/product-import.spec.coffee
test/product-import.spec.coffee

Resolves #101 
Functionality in this PR goes through all variants and filters out duplicate attributes (matched by name) and leaving only the first occurrence.
- Tests

feat(productImport): Add filtering duplicate attributes

---

Gruntfile.coffee
lib/product-import.coffee
test/product-import.spec.coffee

fix(importer): invalid sku predicate

---

lib/price-import.coffee
test/integration/price-import.spec.coffee

Fixes #107
This PR updates how the `unknownSKUs` field is being counted plus it changes final summary message because if there are no updates it does not print out other counts (like `unknownSKUs` or `variantWithoutPriceUpdates`).
- Tests

fix(price-import): Fix unknownSKUsCount in summary report

---

lib/ensure-default-attributes.coffee
lib/product-import.coffee
package.json
test/ensure-default-attributes.spec.coffee

Fixes #112 
This PR fixes using defaultAttributes which are being overwritten by other values.
- Tests

Wrong value of a default attribute

---

package.json
test/price-import.spec.coffee

117 change price action

---

dist/product-import.js
lib/product-import.coffee
package.json
test/integration/product-import.spec.coffee

In this PR I filter out products for which reassignment failed from next processing

feat(product-import): Filter out failed products #116

---

lib/product-import.coffee
test/product-import.spec.coffee

Fixes: https://github.com/sphereio/sphere-product-import/issues/131

fix(productImport): return the summary array for _processBatch

---

package-lock.json
package.json

chore(product-import): update deps

---

lib/product-import.coffee

Adds masterVariant.sku to the error message.
Fixes: https://github.com/sphereio/sphere-product-import/issues/142

fix(productImport): add sku to error

---

lib/product-import.coffee

PR expands the error object so we can see it fully when logged out
- Tests
resolves #144

fix: log full error messages

---

package-lock.json
package.json

Bump reassignment module dependency

chore(product-import): update reassignment module dependency

---

lib/product-import.coffee
readme/product-import.md
test/product-import.spec.coffee

Add before update or create callback.
Fixes: https://github.com/sphereio/sphere-product-import/issues/165

feature(product-import): add before update or create callback

---

lib/product-import.coffee
package-lock.json
package.json
readme/product-import.md
test/integration.spec.coffee
test/integration/product-import.spec.coffee

Add support for matchVariantsByAttr, the issue is described in here: https://github.com/sphereio/sphere-product-import/issues/178
- Tests

feat(product-import): support matchVariantsByAttr option.

---

lib/product-import.coffee
package.json
test/integration/product-import.spec.coffee

Fixes: https://github.com/sphereio/sphere-product-import/issues/181

fix(product-import): fix race condition on product update (#181)

---

package-lock.json
package.json

Update node variant reassignment dependency (https://www.npmjs.com/package/commercetools-node-variant-reassignment)

Upgrade variant reassignment dep
