lib/product-discount-import.coffee
lib/product-import.coffee
package.json
test/integration.spec.coffee
test/integration/price-import.spec.coffee
test/integration/product-discount-import.spec.coffee
test/price-import.spec.coffee
test/product-import.spec.coffee

* does not stop process on error
* skips the products with errors
* logs the error message
* writes the complete error message with the original request to a file in the {current directory}/errors/error-x.json

Update -> continue on error, write all errors to separate file.

---

lib/product-import.coffee
samples/sample-product-type.json
test/integration.spec.coffee
test/product-import.spec.coffee

For every product extracts attribute names of type sameForAll from the product type and passes the names as an argument to the build action method of sync module.

Same for all attribute update

---

lib/product-import.coffee
package.json
test/integration.spec.coffee
test/product-import.spec.coffee

Product Importer can be configured with desired whitelist and blacklist of action groups available for Product Sync.
The following pull request needs to be merged and released before this update will work:  
https://github.com/sphereio/sphere-node-sdk/pull/82

Product Sync whitelist and blacklist configurable

---

samples/sample-product-type.json
samples/sample-products.json
test/integration.spec.coffee

input values are handled correclty: 
```javascript
{
"name": "sample_set_text",
"value": ["set_text_1"]
},
{
"name": "sample_set_text_2",
"value": ["text_1", "text_2", "text_3"]
}
```

Add -> test to check handling of set type attribute values.

---

lib/product-import.coffee
test/product-import.spec.coffee

Option to ignore slug updates by replacing the slug with the slug of existing product.
reason: https://github.com/sphereio/sphere-product-import/issues/48

Ignore slug updates

---

lib/common-utils.coffee
lib/enum-validator.coffee
lib/index.coffee
lib/product-import.coffee
samples/sample-product-type.json
test/common-utils.spec.coffee
test/enum-validator.spec.coffee
test/integration.spec.coffee
test/product-import.spec.coffee

To ensure that any new enum keys received in the product data are added to the product type, before the product data is imported.

Ensure enums in product type

---

lib/product-import.coffee
lib/unknown-attributes-filter.coffee
test/integration.spec.coffee
test/unknown-attributes-filter.spec.coffee

If `filterUnknownAttributes` is enabled
Summary will have a list of ignored attribute names.

Add unknown attribute names to summary.

---

lib/ensure-default-attributes.coffee
lib/index.coffee
lib/price-import.coffee
lib/product-import.coffee
readme/product-import.md
test/ensure-default-attributes.spec.coffee
test/product-import.spec.coffee

Feature to specify a list of default attributes in all product variants.
* All variants are checked for the existence of default attributes 
* If not present, default attributes are added to the attributes list with specified default values
Use Case:
There are some attributes added to the variants by us for various requirements of handling and filtering product data on the frontend as well as for conditional checks by other sub processes such as stock import checking for certain attributes. These extra attributes are not provided in the export from the customers as they do not know about these attributes. 
So it will be good to add these default attributes at the time of product import.

Add -> ensure default attributes in product variants.

---

package.json

@panshul007 I changed the sdk version range from using tilda `~` to using caret `^`. Now we don't have to update the `sphere-product-import` everytime we add a new feature to the SDK. Since we follow SemVer very strictly in the SDK, so no breaking changes will occur unexpectedly when updating the `product-import`er.

bump version for enhanced transition state actions

---

lib/product-import.coffee
package.json
test/integration/product-import.spec.coffee
test/integration/test-helper.coffee

This PR fixes #83 - it splits update actions into smaller chunks (max 500 actions per one chunk) and send them to API one by one.
- Tests

fix(productImport): Fix max 500 update actions per update request error

---

lib/product-import.coffee
test/integration/product-import.spec.coffee
test/product-import.spec.coffee

Resolves #106 
This PR refactors how the existing products are fetched.
Also, I noticed that there is currently no way how to use this module for updating of an existing product which does not have a SKU. But I guess it is not in the scope of this issue.
- Tests

refactor(productImport): Do not send an unnecessary request

---

lib/product-import.coffee
readme/product-import.md
test/integration/product-import.spec.coffee
test/product-import.spec.coffee

Resolves #111 
This PR filters out products which do not have SKUs so they won't be created even if they already exist on the API. It is because we are currently using only SKU to check for a product existence.
- Tests

Restrict this tool to be used only with products which have SKU

---

lib/price-import.coffee
readme/price-importer.md
test/integration/price-import.spec.coffee
test/price-import.spec.coffee

This PR adds a possibility to remove specific prices by setting an empty string to `centAmount` property. It also adds a `deleteOnEmpty` config variable which enables this behavior.
Resolves #123
- Tests

feat(price-import): Prices removal

---

lib/price-import.coffee
package.json
test/integration/price-import.spec.coffee
test/price-import.spec.coffee
test/resources/product-prices.json
test/resources/product.json

Fixes #128 
This PR changes how we generate update actions when syncing prices - old sync module generated `remove` and `add` actions for prices which changed its position in prices array.
New [sync module](https://github.com/commercetools/nodejs/tree/master/packages/sync-actions) matches prices based on their properties.
- Tests

Fix price import error - duplicate price scope

---

lib/price-import.coffee

When requesting more product projections than [default 50](https://github.com/sphereio/sphere-node-sdk/blob/276d47e8d8870894773c2d242efedbbc321fc7f5/src/coffee/connect/rest.coffee#L196) we never set a higher limit which makes the price-importer fail because of a bug within the [sphere-node-sdk](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/connect/rest.coffee#L227) where we keep accumulating results and never break out of the loop... 
PR fixes this by passing the global `@batchSize` to `perPage()` client method. This is then the same size as the `batchedList` and will keep the size consistent.
resolves #133

fix(price-import): add missing query limit to fetch call

---

lib/product-import.coffee

PR makes sure we only print this warning once as it otherwise floods the terminal.
resolves #135

fix: only print logger warning of error limit once

---

lib/common-utils.coffee
lib/product-import.coffee
test/integration/product-import.spec.coffee
test/product-import.spec.coffee

Fixes #5 
This PR fixes a method for fetching of existing products which could potentially return one product multiple times if it was fetched in multiple requests.
It adds also a test for query limit which on API is now [set to 15kb](https://docs.commercetools.com/http-api#disallowed-requests). In the importer, we have a code which breaks SKUs to multiple groups so there are no requests exceeding this limit.
In fact, it now ensures that the maximum URI length is 8192 so even if we combine it with headers, it should not exceed this limit.
@butenkor @lojzatran - could you please check whether this issue still persists?
- Tests

Filter out duplicate products when fetching multiple batches, add test for query limit

---

package-lock.json
package.json

This PR bumps variant reassignment module to [v1.1.3](https://github.com/commercetools/commercetools-node-variant-reassignment/releases/tag/v1.1.3) which fixes problems with an undefined `ctpProductToUpdate` variable.

chore(package.json): bump variant reassignment module to v1.1.3

---

lib/price-import.coffee
test/price-import.spec.coffee

PR introduces a feature to remove properties that got empty values.
When we are passing in empty strings to the importer it would still include these, which then returned errors from the platform. One example is `country` which requires a correct `country code` string.
```
{ code: 'InvalidJsonInput',
message: 'Request body does not contain valid JSON.',
detailedErrorMessage:
'actions -> price -> country: ISO 3166-1 country code expected.' 
}
```
The `_removeEmptyPriceValues` method will remove these and also make sure to keep the `value` property as we need an empty `centAmount` string there to remove prices [(ref)](https://github.com/sphereio/sphere-product-import/blob/d70f27521817455224ab3354244b442c42d3ec2f/lib/price-import.coffee#L125).
- Tests
resolves #150

feat(price-import):  remove empty properties

---

lib/product-import.coffee

This PR increases the log depth level in error logs
FIxes #144 
Logs before:
Logs after:

chore(logger): Increase log depth level

---

package-lock.json
package.json

Use the newest version of variant reassignment dependency: https://github.com/commercetools/commercetools-node-variant-reassignment/releases/tag/v1.1.4

Bump dependency

---

lib/product-import.coffee

In our projects, sometimes we get this the error message: `"Unhandled rejection TypeError: Cannot read property '0' of undefined.`
It could mean one of the 2 options:
1. platform delivers empty response
2. the sphere product import processes the response wrongly and didn’t add `result.body`
In this PR, I added more detailed logs so it's easier to investigate next time we got an error.

fix(product-import): add check for empty results from CTP

---

lib/product-import.coffee
readme/product-import.md
test/product-import.spec.coffee

After a consultation with the team I decided to make a change in the before create and update callback. Now it's split into 2 different callbacks and before update callback also receives list of update actions.
Fixes: https://github.com/sphereio/sphere-product-import/issues/165

feature(product-import): add before create and before update callbacks

---

package-lock.json
package.json

After changing the node-sdk we forgot to change the product-import, could we make a release also for the product-import ?

bump sphere-node-sdk library from 3.0.0 to 3.1.0.

---

lib/product-import.coffee
package-lock.json
package.json

During variant reassignment query products by slug (https://github.com/commercetools/commercetools-node-variant-reassignment/blob/407eda26b5680fc5711432b1a956dc030a7be895/lib/services/product-manager.js#L120) only by the specified list of locales passed to the library. In case the list is empty the behavior should stay as is.
For that, I published the option enhancements for the variant-reassingment project: https://www.npmjs.com/package/commercetools-node-variant-reassignment/v/1.1.5

Add the allowedLocales reassignment option.

---

lib/product-import.coffee
package-lock.json
package.json
test/product-import.spec.coffee

Sometimes in the returned products contain nulls or undefined objects. Then on these null objects a getter is called and this causes NPE. I made a fix for this problem.

Fix error when returned products contain nulls

---

lib/price-import.coffee

Currently we don't support key in the csv for price import so this PR make sure we are supporting key as well.

feat: support key for customerGroupPredicate

---

lib/product-import.coffee
package-lock.json
test/integration.spec.coffee
test/product-import.spec.coffee

When [resolving references](https://github.com/commercetools/sphere-product-import/blob/c02829254002eb3ffc0bcd554b5cc46833949db9/lib/product-import.coffee#L734), sometimes it returns Stringified JSON and this is not expected result. This causes the process to fail.
As this happens rarely and on retry it usually works, I added a retry.

Add retry when resolving references
